# Use Node.js Alpine base image
FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY aplikacija/backend/package*.json ./
RUN npm install

# Copy source code
COPY aplikacija/backend ./

# Expose the backend port
EXPOSE 3000

# Start the backend server
CMD ["npm", "start"]
