# Ime pipeline-a za backend
name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: aplikacija/backend/node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('aplikacija/backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install dependencies
      run: |
        cd aplikacija/backend
        npm ci

    - name: Wait for MySQL to be ready
      run: |
        for i in {60..0}; do
          if mysqladmin ping -h 127.0.0.1 --silent; then
            break
          fi
          echo "Waiting for MySQL to initialize..."
          sleep 1
        done

    - name: Initialize database
      run: |
        mysql --host=127.0.0.1 --user=testuser --password=testpassword testdb < aplikacija/db/db_setup.sql

    - name: Run tests with coverage
      run: |
        cd aplikacija/backend
        npm run test:ci -- --detectOpenHandles

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: aplikacija/backend/coverage/

    - name: Build backend
      run: echo "No build step for backend"

    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: aplikacija/backend/build
