name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - production

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # name: Install Dependencies
      #  run: |
      #    cd aplikacija
       #   npm install

      - name: Build Application
        run: |
          cd aplikacija
          npm run build

      - name: Build Docker Image
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG="latest"
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            TAG="production"
          fi
          docker build -t Galicius/frontend:$TAG -f Dockerfile.frontend .
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push Galicius/frontend:${{ env.TAG }}
